FROM edilsonathayde/trino:lakehouse-arm64-457

COPY hive.properties /etc/trino/catalog/hive.properties
COPY delta.properties /etc/trino/catalog/delta.properties
COPY iceberg.properties /etc/trino/catalog/iceberg.properties
COPY postgres.properties /etc/trino/catalog/postgres.properties
